apiVersion: v1
kind: Secret
metadata:
  name: db-secret-postgres
  namespace: ${param.namespace}
type: Opaque
stringData:
  db.server.name: ${param.db.server.name}
  db.port.number: "${param.db.port.number}"
  db.name: ${param.db.name}
  db.user: ${param.db.user}
  db.password: ${param.db.password}
