apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-postgres
  namespace: ${param.namespace}
spec:
  replicas: 3
  applicationImage: javaee-cafe-postgres:v1
  pullPolicy: Always
  expose: true
  env:
    - name: DB_SERVER_NAME
      valueFrom:
        secretKeyRef:
          name: db-secret-postgres
          key: db.server.name
    - name: DB_PORT_NUMBER
      valueFrom:
        secretKeyRef:
          name: db-secret-postgres
          key: db.port.number
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-secret-postgres
          key: db.name
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret-postgres
          key: db.user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret-postgres
          key: db.password
