apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-cluster-session-persistence-db
  namespace: open-liberty-demo
spec:
  # Note: replace "${REPLICAS}" with number of pods to be created
  replicas: ${REPLICAS}
  applicationImage: javaee-cafe-session-persistence-db:1.0.0
  expose: true
  env:
  - name: SHOW_HOST_NAME
    value: 'true'
  - name: DB_SERVER_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.server.name
  - name: DB_PORT_NUMBER
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.port.number
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.password
