apiVersion: v1
kind: Secret
metadata:
  # - replace "${DB_Type}" with "mssql" for testing DB connection with Azure SQL
  # - replace "${DB_Type}" with "postgres" for testing DB connection with Azure Database for PostgreSQL
  name: db-secret-${DB_Type}
  namespace: open-liberty-demo
type: Opaque
stringData:
  db.server.name: ${DB_SERVER_NAME}
  db.port.number: "${DB_PORT_NUMBER}"
  db.name: ${DB_NAME}
  db.user: ${DB_USER}
  db.password: ${DB_PASSWORD}
