apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  # Note:
  # - replace "${DB_Type}" with "mssql" for testing DB connection with Azure SQL
  # - replace "${DB_Type}" with "postgres" for testing DB connection with Azure Database for PostgreSQL
  name: javaee-cafe-cluster-connect-db-${DB_Type}
  namespace: open-liberty-demo
spec:
  # Note: replace "${REPLICAS}" with number of pods to be created
  replicas: ${REPLICAS}
  # Note: 
  # - replace "${Image_Name}" with "javaee-cafe-connect-db-mssql" for testing DB connection with Azure SQL
  # - replace "${Image_Name}" with "javaee-cafe-connect-db-postgres" for testing DB connection with Azure Database for PostgreSQL
  applicationImage: ${Image_Name}:1.0.0
  expose: true
  # Note:
  # - replace "${DB_Type}" with "mssql" for testing DB connection with Azure SQL
  # - replace "${DB_Type}" with "postgres" for testing DB connection with Azure Database for PostgreSQL
  env:
  - name: SHOW_HOST_NAME
    value: 'true'
  - name: DB_SERVER_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-${DB_Type}
        key: db.server.name
  - name: DB_PORT_NUMBER
    valueFrom:
      secretKeyRef:
        name: db-secret-${DB_Type}
        key: db.port.number
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-${DB_Type}
        key: db.name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-secret-${DB_Type}
        key: db.user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret-${DB_Type}
        key: db.password
