apiVersion: v1
kind: Secret
metadata:
  name: db-secret-postgres
  namespace: open-liberty-demo
type: Opaque
stringData:
  db.server.name: ${DB_SERVER_NAME}
  db.port.number: "${DB_PORT_NUMBER}"
  db.name: ${DB_NAME}
  db.user: ${DB_USER}
  db.password: ${DB_PASSWORD}
