apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-session-persistence-jcache
  namespace: open-liberty-demo
spec:
  replicas: 3
  applicationImage: javaee-cafe-session-persistence-jcache:1.0.0
  expose: true
  service:
    port: 9443
    certificateSecretRef: tls-crt-secret
  route:
    termination: reencrypt
    certificateSecretRef: tls-crt-secret
  env:
  - name: WLP_LOGGING_CONSOLE_FORMAT
    value: SIMPLE
  - name: DB_SERVER_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.server.name
  - name: DB_PORT_NUMBER
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.port.number
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret-postgres
        key: db.password
  volumeMounts:
  - name: redisson-config
    mountPath: /config/redisson-config.yaml
    readOnly: true
    subPath: redisson-config.yaml
  volumes:
  - name: redisson-config
    secret:
      secretName: redisson-config-secret
