apiVersion: v1
kind: Secret
metadata:
  name: aad-ldap-secret
  namespace: open-liberty-demo
type: Opaque
stringData:
  ldap.server.host: ${LDAP_SERVER_HOST}
  ldap.server.port: "${LDAP_SERVER_PORT}"
  ldap.server.baseDN: "${LDAP_SERVER_BASEDN}"
  ldap.server.bindDN: "${LDAP_SERVER_BINDDN}"
  ldap.server.bindPassword: ${LDAP_SERVER_BINDPASSWORD}
  keystore.name: ${KEYSTORE_NAME}
  keystore.pass: ${KEYSTORE_PASS}
  admin.group.name: ${ADMIN_GROUP_NAME}
