apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-aad-ldap
  namespace: open-liberty-demo
spec:
  replicas: 1
  applicationImage: javaee-cafe-aad-ldap:1.0.0
  expose: true
  service:
    port: 9443
    certificateSecretRef: tls-crt-secret
  route:
    termination: reencrypt
    certificateSecretRef: tls-crt-secret
  env:
  - name: KEY_ALIAS
    value: 'defaultkeystore'
  - name: LDAP_SERVER_HOST
    valueFrom:
      secretKeyRef:
        name: aad-ldap-secret
        key: ldap.server.host
  - name: LDAP_SERVER_PORT
    valueFrom:
      secretKeyRef:
        name: aad-ldap-secret
        key: ldap.server.port
  - name: LDAP_SERVER_BASEDN
    valueFrom:
      secretKeyRef:
        name: aad-ldap-secret
        key: ldap.server.baseDN
  - name: LDAP_SERVER_BINDDN
    valueFrom:
      secretKeyRef:
        name: aad-ldap-secret
        key: ldap.server.bindDN
  - name: LDAP_SERVER_BINDPASSWORD
    valueFrom:
      secretKeyRef:
        name: aad-ldap-secret
        key: ldap.server.bindPassword
  - name: KEYSTORE_NAME
    valueFrom:
      secretKeyRef:
        name: aad-ldap-secret
        key: keystore.name
  - name: KEYSTORE_PASS
    valueFrom:
      secretKeyRef:
        name: aad-ldap-secret
        key: keystore.pass
  - name: ADMIN_GROUP_NAME
    valueFrom:
      secretKeyRef:
        name: aad-ldap-secret
        key: admin.group.name
  volumeMounts:
  - name: config
    mountPath: /config/${KEYSTORE_NAME}
    readOnly: true
    subPath: ${KEYSTORE_NAME}
  volumes:
  - name: config
    configMap:
      defaultMode: 0600
      name: keystore-config
