apiVersion: v1
kind: Secret
metadata:
  name: tls-crt-secret
  namespace: open-liberty-demo
type: kubernetes.io/tls
data:
  ca.crt: ${CA_CRT}
  destCA.crt: ${DEST_CA_CRT}
  tls.crt: ${TLS_CRT}
  tls.key: ${TLS_KEY}
