apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-ssl-reencrypt
  namespace: open-liberty-demo
spec:
  replicas: 3
  applicationImage: javaee-cafe-ssl:1.0.0
  pullPolicy: Always
  expose: true
  service:
    port: 9443
    ports:
      - port: 9080
        targetPort: 9080
        name: http
    certificateSecretRef: tls-crt-secret
  route:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
    certificateSecretRef: tls-crt-secret
