apiVersion: v1
kind: Secret
metadata:
  name: db-secret-mysql
  namespace: open-liberty-demo
type: Opaque
stringData:
  db.server.name: ${param.db.server.name}
  db.port.number: "3306"
  db.name: ${param.db.name}
  db.user: ${param.db.user}
  db.password: ${param.db.password}
