apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: ${project.artifactId}
  namespace: ${param.namespace}
spec:
  replicas: ${param.replicas}
  applicationImage: ${project.artifactId}:${project.version}
  pullPolicy: Always
  expose: true
  env:
    - name: DB_SERVER_NAME
      valueFrom:
        secretKeyRef:
          name: db-secret-mysql
          key: db.server.name
    - name: DB_PORT_NUMBER
      valueFrom:
        secretKeyRef:
          name: db-secret-mysql
          key: db.port.number
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-secret-mysql
          key: db.name
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret-mysql
          key: db.user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret-mysql
          key: db.password
