apiVersion: v1
kind: Secret
metadata:
  name: elastic-cloud-secret
  namespace: open-liberty-demo
type: Opaque
stringData:
  elastic.cloud.id: ${ELASTIC_CLOUD_ID}
  elastic.cloud.auth: ${ELASTIC_CLOUD_AUTH}
