apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: javaee-cafe-connect-db-mssql
  namespace: open-liberty-demo
spec:
  replicas: 1
  # Note: replace "${Your_DockerHub_Account}" with your Docker Hub account name
  applicationImage: docker.io/${Your_DockerHub_Account}/javaee-cafe-connect-db-mssql:latest
  expose: true
  env:
  - name: DB_SERVER_NAME
    valueFrom:
      secretKeyRef:
        name: mssql-secret
        key: db.server.name
  - name: DB_PORT_NUMBER
    valueFrom:
      secretKeyRef:
        name: mssql-secret
        key: db.port.number
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: mssql-secret
        key: db.name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: mssql-secret
        key: db.user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mssql-secret
        key: db.password
