name: Setup DB and Storage Account

on:
  workflow_dispatch:
  repository_dispatch:

env:
    refJavaee: bce4e6ec57726d4bc7992b45e1ff6e459b02fb39
    azCliVersion: 2.23.0
    azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
    location: eastus
    resourceGroupForDB: wlsd-db-${{ github.run_id }}-${{ github.run_number }}
    dbName: db${{ github.run_id }}${{ github.run_number }}
    dbAdminUser: admin
    dbPassword: ${{ secrets.DB_PASSWORD }}

jobs:
    preflight:
        runs-on: ubuntu-latest
        steps:
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
    deploy-db:
        needs: preflight
        runs-on: ubuntu-latest
        steps:
            - uses: azure/login@v1
              id: azure-login
              with:
                creds: ${{ env.azureCredentials }}
            - name: Create Resource Group
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    echo "create resource group" ${{ env.resourceGroupForDB }}
                    az group create --verbose --name ${{ env.resourceGroupForDB }} --location ${{ env.location }}
            - name: Set Up Azure Postgresql to Test dbTemplate
              id: setup-postgresql
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    echo "Deploy DB with name " ${{ env.dbName }}
                    az postgres server create \
                    --resource-group ${{ env.resourceGroupForDB }} \
                    --name ${{ env.dbName }}  \
                    --location ${{ env.location }} \
                    --admin-user ${{ env.dbAdminUser }} \
                    --ssl-enforcement Enabled \
                    --public-network-access Enabled \
                    --admin-password ${{ env.dbPassword }} \
                    --sku-name B_Gen5_1
                    echo "Allow Access To Azure Services"
                    az postgres server firewall-rule create \
                    -g ${{ env.resourceGroupForDB }} \
                    -s ${{ env.dbName }} \
                    -n "AllowAllWindowsAzureIps" \
                    --start-ip-address "0.0.0.0" \
                    --end-ip-address "0.0.0.0"
